name: Android CI

on:
  pull_request:
    branches: [ "develop_android" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    - name: Check ktlint format
      run: ./gradlew ktlintCheck
      working-directory: ${{ env.working-directory }}

